### ISSUE TITLE
This is not your plugin

### ISSUE THREAD

**Issue by TheFixerDevelopment** [AlexPads/WildCustom#1]
Hi, I just wanted to tell you that you did not write this plugin. So why credit yourself? You never coded this plugin nor do you own this plugin.
This plugin was originally created by SkyLightMCPE.
iZeaoGamer basically added in the configurations, and stuff. And you go and copy the stuff they've put into this plugin? Like tf? You shouldn't be doing that, and I can give you a link to the original updated version of this plugin here:
https://github.com/iZeaoGamer/Wild
That's the config support version.
So just stop, and remove this plugin before anything get's worse.
Oof, people these days, why the fuck do they take credit for something they never did? I bet he just copied iZeaoGamer's config option support.
Take this off github now.

**Comment by AlexPads** [comment]
Copied the Support? how and why would I want to do that Just saying... 


but I will stop trying to release it Because I have something better to release anyways and because you all can't accept that I didn't copy this plugin so whatever its not that great anyways......
